### ISSUE TITLE
Where is the xposed module/ magisk module , no download link on the website !

### ISSUE THREAD

**Issue by alokbhaisahu** [Xposed-Modules-Repo/com.alex193a.ivdisabler#2]
You say the magisk module is available for download on your website but there is no download button there https://xposed.alex193a.com/download/integrity-verification-disabler/

**Comment by Tahirpatel12345** [comment]
Same problem

**Comment by alex193a** [comment]
The magisk module can be downloaded here: https://modules.alex193a.com/magisk/
